sudo: required
notifications:
  email: false
services:
  - docker
language: node_js
node_js:
  - stable
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - npm run build
  # deploy, only if on master
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
    --password-stdin && make build && make push; fi
